Add Bluetooth cancel functionality
ericcornelissen/NervousFish pull request #318
Opened 2017-06-22 16:45 UTC by ericcornelissen

- Relevant Issues: #278
- Related Pull Requests: -

* * *

## What

This Pull Request adds to the repository functionality to actually cancel the Bluetooth connection. Either by pressing the Cancel button in the `WaitingActivity` or the back button in any of the activities that appear in the Bluetooth connection process

## Why

This Pull Request is needed because it makes it possible to cancel a Bluetooth connection whenever a user wants to. Besides that it also makes it so the actual connection is stopped, not just the activities.

## How

This feature can be viewed/tested within the project by starting a Bluetooth connection and trying to cancel it from every activity. Be sure to check if you can immediately start a new connection, as this shows that the previous connection has been canceled.

## Alternative implementation

None considered

## Notes

Not sure if `this.serviceLocator.getBluetoothHandler().stop();` is the correct way to stop a Bluetooth connection 🤔

2017-06-22 17:28 UTC, jverbraeken approved these changes

2017-06-22 17:28 UTC, jverbraeken commented
@ericcornelissen Did you test if this code works?

2017-06-22 22:08 UTC, ericcornelissen commented
I did not 😅 Sorry, should've been more clear about that

2017-06-23 11:57 UTC, TheBonheurs approved these changes

2017-06-23 14:33 UTC, clenrock requested changes
Does not work as intended yet

2017-09-19 15:11 UTC, closed without merging